import assert from 'node:assert/strict';
process.env.DATABASE_URL ||= 'postgresql://test:test@127.0.0.1:1/test';
const {manualSarf}=await import('../server/sarf');
const {sarfProcess}=await import('../server/sarf-process');
const result=await manualSarf({past:'خَافَ',root:'خوف',futureType:'فتحة',triliteral:true,transitive:false});
assert.equal(result.tables.command[0][6],'خَفْ');assert(result.verb.manual);assert.equal(result.verb.meaning,'');assert(!('tables' in result.verb));
for(const past of ['كتب','كَتبَ','<script>','كَتَبَ; touch /tmp/bad'])await assert.rejects(()=>manualSarf({past,root:'كتب',futureType:'ضمة',triliteral:true,transitive:true}));
await assert.rejects(()=>manualSarf({past:'أَكْرَمَ',root:'كرم',futureType:'فتحة',triliteral:true,transitive:true}));
const found=await sarfProcess<{ids:number[]}>('lookup',{query:'قُلْتُ'});assert(found.ids.includes(-10095));
console.log('Real Node/Python protocol, manual validation, hollow correction and reverse lookup passed.');

const written=await sarfProcess<{ids:number[];matches:Record<string,string[]>}>('lookup',{query:'كَتَبْتُ'});
assert(written.ids.includes(-10136));assert(!written.ids.includes(-1552));
assert.deepEqual(written.matches['-10136'],['كَتَبْتُ']);
const ambiguous=await sarfProcess<{ids:number[];matches:Record<string,string[]>}>('lookup',{query:'كتبت'});
assert(ambiguous.ids.includes(-10136));assert(ambiguous.ids.includes(-1552));
assert(ambiguous.matches['-10136'].includes('كَتَبْتُ'));
const attain=await sarfProcess<{ids:number[];matches:Record<string,string[]>}>('lookup',{query:'يَنَالُونَ'});
assert.deepEqual(attain.ids,[-20002]);assert.deepEqual(attain.matches['-20002'],['يَنَالُونَ']);
const absent=await sarfProcess<{ids:number[]}>('lookup',{query:'zzzz'});assert.deepEqual(absent.ids,[]);
console.log('Inflected dictionary lookup: vocalization, ambiguity, canonical forms and absent queries passed.');
