import assert from 'node:assert/strict';
import {buildSarfBook} from '../shared/sarf-book';
import {sarfBookSchema} from '../shared/sarf-export';
import type {SarfDetail} from '../shared/sarf-expanded';
const col=(s:string)=>Array.from({length:14},(_,i)=>`${s}${i}`);
const d:SarfDetail={verb:{id:1,past:'كَتَبَ',present:'يَكْتُبُ',root:'كتب',form:'I',kind:'Solim',futureType:'ضمة',triliteral:true,transitive:true,meaning:'yozmoq',source:'Lug‘at',masdar:'كِتَابَةٌ',meanings:[],entryIds:[]},tables:{active:[0,1,2,3].map(i=>col('a'+i)),passive:[0,1,2,3].map(i=>col('p'+i)),command:[col('c'),col('n')],emphasis:{active:[col('ah'),col('al')],passive:[col('ph'),col('pl')],command:[col('ch'),col('cl')]},nominals:{subject:'كَاتِبٌ',object:'مَكْتُوبٌ',subjectLabel:'Ismi foil',note:''}}};
const b=buildSarfBook(d);
assert(sarfBookSchema.safeParse(b).success);
assert.equal(b.sections.length,17);
assert.equal(b.sections[0].rows.length,14);
assert.deepEqual(b.sections[0].rows[13].slice(1),['a013','p013']);
assert.equal(b.sections[2].rows[0][1],'لَنْ a20');
assert.equal(b.sections[3].rows[0][2],'لَمْ p30');
assert.deepEqual(b.sections[4].rows.map(r=>r[1]),d.tables.command[0].slice(6,12));
assert.equal(b.sections[7].rows[13][2],'pl13');
assert.deepEqual(b.sections[8].rows[0].slice(1),['ch6','cl6']);
assert.equal(b.sections[13].rows[0][1],'لَمَّا a30');
assert.equal(b.sections[14].rows.length,6);assert.equal(b.sections[15].rows.length,6);
assert.equal(b.sections[16].rows[0][1],'كِتَابَةٌ');
d.tables.passive=null;d.tables.emphasis.passive=null;d.tables.nominals.object=null;d.verb.masdar='';
const intr=buildSarfBook(d);assert(sarfBookSchema.safeParse(intr).success);
assert.equal(intr.sections.length,16);assert.equal(intr.sections[0].rows[0][2],'—');
assert.equal(intr.sections[15].rows[0][1],'—');
assert(!sarfBookSchema.safeParse({...b,sections:Array(21).fill(b.sections[0])}).success);
console.log('All PDF sections, passive/active, pronouns, particles, emphasis, nouns, masdar and unavailable forms: passed');
